FEATURE_CONFIG = {
    "MARKET_STRUCTURE_WINDOW": 100,
    "ORDER_BLOCKS_WINDOW": 50,
    "FVG_WINDOW": 30,
    "ORDER_FLOW_WINDOW": 1000,
    
    "TIMEFRAMES": ["1h", "15m", "5m", "1m"],
    "PRIMARY_TIMEFRAME": "15m",
    
    "ADX_HARD_REJECT": 10.0,
    "ADX_STRONG_PENALTY": 15.0,
    "ADX_MEDIUM_PENALTY": 20.0,
    "MIN_TREND_STRENGTH": 0.3,
    
    "RSI_PERIOD": 14,
    "MACD_FAST": 12,
    "MACD_SLOW": 26,
    "MACD_SIGNAL": 9,
    "ATR_PERIOD": 14,
    
    "FEATURE_UPDATE_INTERVAL": 1.0,
    "FEATURE_CACHE_TTL": 300,
}
