LEARNING_CONFIG = {
    "EXPLORATION_PHASE_TRADES": 50,
    "EXPLOITATION_PHASE_TRADES": 200,
    
    "BOOTSTRAP_MIN_WIN_RATE": 0.40,
    "BOOTSTRAP_MIN_CONFIDENCE": 0.40,
    "BOOTSTRAP_SIGNAL_QUALITY": 0.4,
    
    "MATURE_MIN_WIN_RATE": 0.60,
    "MATURE_MIN_CONFIDENCE": 0.50,
    "MATURE_SIGNAL_QUALITY": 0.6,
    
    "INITIAL_LEARNING_RATE": 0.1,
    "LEARNING_RATE_DECAY": 0.95,
    "MIN_LEARNING_RATE": 0.01,
    
    "EXPLORATION_PROBABILITY": 0.3,
    "EXPLORATION_DECAY": 0.99,
}
