WEBSOCKET_CONFIG = {
    "MAX_LATENCY": 0.1,
    "BUFFER_SIZE": 1000,
    "RECONNECT_DELAY": 1.0,
    "HEARTBEAT_INTERVAL": 30.0,
    
    "SHARD_SIZE": 50,
    "MAX_SHARDS": 10,
    "SHARD_RECONNECT_DELAY": 2.0,
    
    "TIMESTAMP_SYNC_INTERVAL": 300.0,
    "MAX_TIMESTAMP_DRIFT": 0.5,
    
    "MESSAGE_BATCH_SIZE": 10,
    "PROCESSING_CONCURRENCY": 5,
    "MEMORY_CLEANUP_INTERVAL": 60,
}
